# 一个workflow，名为deploy
name: deploy

on: # 此CI/CD触发时的事件
  push: # 在代码提交时自动触发
    branches:
      - main

# 一个 CI/CD 的工作流有许多 jobs 组成，比如最典型的 job 是 lint，test，build。
jobs: 
  build: # 构建job
    runs-on: ubuntu-latest # 跑workflow的服务器系统
    steps: # job的一系列动作
      # 切换分支获取源码
      - name: Checkout # step的名称，将会在 github action 的控制台中显示
        # 选择一个action，可以理解为若干 steps.run，有利于代码复用
        uses: actions/checkout@main
      # 安装使用 node:10
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10
      # 运行命令，npm install && npm run build
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      - name: Rsync Deployments Action
        uses: Burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: src/
          remote_path: /www/server/nginx/html/life
          remote_host: 42.193.137.196
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}

